pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                echo 'Building..'
                // sh './mvnw -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
                sh './mvnw verify'
                junit "./target/surefire-reports/*.xml/"
"
            }
        }
        stage('ChangeContro'){
            steps{
                echo "Change Control"
                snDevOpsChange()
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
                // ash './mvnw compile jib:build -s .pipeline/maven_setting.xml'
            }
        }
    }
}
