pipeline {
    agent : any

    stages {
        stage('Build') {
            steps {
                echo 'Building..'
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
                sh 'mvn verify'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
                sh './mvnw compile jib:build -s .pipeline/maven_setting.xml'
            }
        }
    }
}
